"""initial schema

Revision ID: b0d71eb010ae
Revises: 
Create Date: 2026-08-05 03:34:21.303126
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b0d71eb010ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitchers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pitchers'))
    )
    op.create_index(op.f('ix_pitchers_full_name'), 'pitchers', ['full_name'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('team_code', sa.String(length=5), nullable=True),
    sa.Column('league', sa.String(length=30), nullable=True),
    sa.Column('division', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=True)
    op.create_table('games',
    sa.Column('game_pk', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=2), server_default='R', nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('venue_name', sa.String(length=80), nullable=True),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doubleheader', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('game_num', sa.Integer(), server_default='1', nullable=False),
    sa.Column('away_probable_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('home_probable_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_runs_1st', sa.Integer(), nullable=True),
    sa.Column('home_runs_1st', sa.Integer(), nullable=True),
    sa.Column('first_inning_runs', sa.Integer(), nullable=True),
    sa.Column('nrfi', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name=op.f('ck_games_teams_differ')),
    sa.ForeignKeyConstraint(['away_probable_pitcher_id'], ['pitchers.id'], name=op.f('fk_games_away_probable_pitcher_id_pitchers')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_games_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_probable_pitcher_id'], ['pitchers.id'], name=op.f('fk_games_home_probable_pitcher_id_pitchers')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_games_home_team_id_teams')),
    sa.PrimaryKeyConstraint('game_pk', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_nrfi'), 'games', ['nrfi'], unique=False)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index('ix_games_season_date', 'games', ['season', 'game_date'], unique=False)
    op.create_table('pitcher_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('batters_faced_1st', sa.Integer(), nullable=True),
    sa.Column('hits_1st', sa.Integer(), nullable=True),
    sa.Column('runs_1st', sa.Integer(), nullable=True),
    sa.Column('earned_runs_1st', sa.Integer(), nullable=True),
    sa.Column('walks_1st', sa.Integer(), nullable=True),
    sa.Column('strikeouts_1st', sa.Integer(), nullable=True),
    sa.Column('home_runs_1st', sa.Integer(), nullable=True),
    sa.Column('pitches_1st', sa.Integer(), nullable=True),
    sa.Column('innings_pitched', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('batters_faced', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('pitches', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], name=op.f('fk_pitcher_game_stats_game_pk_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitcher_id'], ['pitchers.id'], name=op.f('fk_pitcher_game_stats_pitcher_id_pitchers')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_pitcher_game_stats_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pitcher_game_stats')),
    sa.UniqueConstraint('game_pk', 'pitcher_id', name='uq_pitcher_per_game')
    )
    op.create_index(op.f('ix_pitcher_game_stats_game_pk'), 'pitcher_game_stats', ['game_pk'], unique=False)
    op.create_index(op.f('ix_pitcher_game_stats_pitcher_id'), 'pitcher_game_stats', ['pitcher_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_label', sa.String(length=4), nullable=False),
    sa.Column('nrfi_probability', sa.Float(), nullable=False),
    sa.Column('yrfi_probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("predicted_label IN ('NRFI', 'YRFI')", name=op.f('ck_predictions_valid_label')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_predictions_confidence_range')),
    sa.CheckConstraint('nrfi_probability >= 0 AND nrfi_probability <= 1', name=op.f('ck_predictions_nrfi_probability_range')),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], name=op.f('fk_predictions_game_pk_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('game_pk', 'model_version', name='uq_prediction_per_model_version')
    )
    op.create_index(op.f('ix_predictions_game_pk'), 'predictions', ['game_pk'], unique=False)
    op.create_index(op.f('ix_predictions_model_version'), 'predictions', ['model_version'], unique=False)
    op.create_table('team_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('runs_1st', sa.Integer(), nullable=True),
    sa.Column('hits_1st', sa.Integer(), nullable=True),
    sa.Column('walks_1st', sa.Integer(), nullable=True),
    sa.Column('strikeouts_1st', sa.Integer(), nullable=True),
    sa.Column('batters_1st', sa.Integer(), nullable=True),
    sa.Column('left_on_base_1st', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('left_on_base', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], name=op.f('fk_team_game_stats_game_pk_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_game_stats_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_game_stats')),
    sa.UniqueConstraint('game_pk', 'team_id', name='uq_team_per_game')
    )
    op.create_index(op.f('ix_team_game_stats_game_pk'), 'team_game_stats', ['game_pk'], unique=False)
    op.create_index(op.f('ix_team_game_stats_team_id'), 'team_game_stats', ['team_id'], unique=False)
    op.create_table('prediction_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('actual_label', sa.String(length=4), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('odds_american', sa.Integer(), nullable=True),
    sa.Column('stake', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actual_label IN ('NRFI', 'YRFI')", name=op.f('ck_prediction_results_valid_actual_label')),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], name=op.f('fk_prediction_results_game_pk_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_prediction_results_prediction_id_predictions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_results')),
    sa.UniqueConstraint('prediction_id', name=op.f('uq_prediction_results_prediction_id'))
    )
    op.create_index(op.f('ix_prediction_results_correct'), 'prediction_results', ['correct'], unique=False)
    op.create_index(op.f('ix_prediction_results_game_pk'), 'prediction_results', ['game_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_results_game_pk'), table_name='prediction_results')
    op.drop_index(op.f('ix_prediction_results_correct'), table_name='prediction_results')
    op.drop_table('prediction_results')
    op.drop_index(op.f('ix_team_game_stats_team_id'), table_name='team_game_stats')
    op.drop_index(op.f('ix_team_game_stats_game_pk'), table_name='team_game_stats')
    op.drop_table('team_game_stats')
    op.drop_index(op.f('ix_predictions_model_version'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_game_pk'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_pitcher_game_stats_pitcher_id'), table_name='pitcher_game_stats')
    op.drop_index(op.f('ix_pitcher_game_stats_game_pk'), table_name='pitcher_game_stats')
    op.drop_table('pitcher_game_stats')
    op.drop_index('ix_games_season_date', table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_nrfi'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_pitchers_full_name'), table_name='pitchers')
    op.drop_table('pitchers')
    # ### end Alembic commands ###
