"""venues table and weather/odds columns

Revision ID: fc4fd0c7dc75
Revises: b0d71eb010ae
Create Date: 2026-08-19 23:03:15.383955
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc4fd0c7dc75'
down_revision: Union[str, None] = 'b0d71eb010ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.add_column('games', sa.Column('weather_temp_f', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('weather_conditions', sa.String(length=60), nullable=True))
    op.add_column('games', sa.Column('weather_wind_mph', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('weather_wind_direction_deg', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('weather_captured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('home_moneyline', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_moneyline', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('odds_bookmaker', sa.String(length=40), nullable=True))
    op.add_column('games', sa.Column('odds_captured_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'odds_captured_at')
    op.drop_column('games', 'odds_bookmaker')
    op.drop_column('games', 'away_moneyline')
    op.drop_column('games', 'home_moneyline')
    op.drop_column('games', 'weather_captured_at')
    op.drop_column('games', 'weather_wind_direction_deg')
    op.drop_column('games', 'weather_wind_mph')
    op.drop_column('games', 'weather_conditions')
    op.drop_column('games', 'weather_temp_f')
    op.drop_table('venues')
    # ### end Alembic commands ###
